version: 2
jobs:

    working_directory: ~/extract_bits

    docker:
      - image: circleci/openjdk:11.0-stretch

    steps:

      - checkout

      - restore_cache:
          key: quick_sort-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: extract_bits-{{ checksum "pom.xml" }}

      - run: mvn clean test

      - store_test_results:
          path: target/surefire-reports
